version: '3.9'

services:

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/aircargo

  db:
    image: postgres:15

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aircargo

    ports:
      - "5432:5432"

  ingestion:
    build: .
    command: >
      sh -c "sleep 15 && while true; do python -m scripts.ingest_opensky; sleep 300; done"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/aircargo


  redis:
    image: redis:7
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  worker:
    build: . 
    command: remoulade app.tasks
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/aircargo
