global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "aircargo-api"
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets:
          - "aircargo-forecasting-platform.onrender.com"
